#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $SCRIPT_DIR
cd ../

LIST=(
  meta-llama/Meta-Llama-3-8B-Instruct
  # meta-llama/Meta-Llama-3-70B-Instruct
  # Trelis/Meta-Llama-3-8B-Instruct-function-calling
  # Trelis/Meta-Llama-3-70B-Instruct-function-calling
)

OUTTYPE=f16
QUANTITY=(
  q3_k_m
  # q4_k_s
  # q4_k_m
  # q5_k_m
)

PYTHON=$(which python3)
if [ -f "${HOMEBREW_PREFIX}/bin/python3" ]; then
  PYTHON="${HOMEBREW_PREFIX}/bin/python3"
fi

for SOURCE in "${LIST[@]}"; do

  if [ ! -f "./models/${SOURCE}/ggml-model-${OUTTYPE}.gguf" ]; then
    mkdir -p ./models/${SOURCE}
    ${PYTHON} packages/llama.cpp/convert_hf_to_gguf.py ./.cache/models/${SOURCE} --outtype ${OUTTYPE} --outfile ./models/${SOURCE}/ggml-model-${OUTTYPE}.gguf
  fi

  for q in "${QUANTITY[@]}"; do
    if [ ! -f "./models/${SOURCE}/ggml-model-${q}.gguf" ]; then
      packages/llama.cpp/llama-quantize ./models/${SOURCE}/ggml-model-f16.gguf ./models/${SOURCE}/ggml-model-${q}.gguf ${q}
    fi
  done

done
