#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $SCRIPT_DIR
cd ../

OUTTYPE=f16
QUANTITY=(
  q3_k_m
  # q4_k_s
  # q4_k_m
  # q5_k_m
)

LLAMA_PREFIX=packages/llama.cpp
LLAMA_BIN=${LLAMA_PREFIX}/.build/bin

PYTHON=$(which python3)
if [ -f "${HOMEBREW_PREFIX}/bin/python3" ]; then
  PYTHON="${HOMEBREW_PREFIX}/bin/python3"
fi

for SRC in ./models/*/*; do
  SOURCE="$( basename "$( dirname "${SRC}" )" )/$( basename "${SRC}" )"

  if [ ! -f "./models/${SOURCE}/ggml-model-${OUTTYPE}.gguf" ]; then
    mkdir -p ./models/${SOURCE}
    ${PYTHON} ${LLAMA_PREFIX}/convert_hf_to_gguf.py ./.cache/models/${SOURCE} --outtype ${OUTTYPE} --outfile ./models/${SOURCE}/ggml-model-${OUTTYPE}.gguf
  fi

  for q in "${QUANTITY[@]}"; do
    if [ ! -f "./models/${SOURCE}/ggml-model-${q}.gguf" ]; then
      ${LLAMA_BIN}/llama-quantize ./models/${SOURCE}/ggml-model-f16.gguf ./models/${SOURCE}/ggml-model-${q}.gguf ${q}
    fi
  done

done
