#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $SCRIPT_DIR
cd ../

LIST=(
  meta-llama/Meta-Llama-3-8B-Instruct
  # meta-llama/Meta-Llama-3-70B-Instruct
  # Trelis/Meta-Llama-3-8B-Instruct-function-calling
  # Trelis/Meta-Llama-3-70B-Instruct-function-calling
)

for SOURCE in "${LIST[@]}"; do
  huggingface-cli download ${SOURCE} --local-dir ./.cache/models/${SOURCE}
done
