#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $SCRIPT_DIR
cd ../

cd llama.cpp
make

PYTHON=$(which python3)
if [ -f "${HOMEBREW_PREFIX}/bin/python3" ]; then
  PYTHON="${HOMEBREW_PREFIX}/bin/python3"
fi

${PYTHON} -m pip install -r requirements.txt --break-system-packages
