name: Test
on: [push, pull_request]
jobs:
  macos:
    name: macos node ${{ matrix.node_version }}
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        node_version: ['18.x', '20.x']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - name: Test rollup
        run: yarn rollup
  ubuntu:
    name: ubuntu node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version: ['18.x', '20.x']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - name: Test rollup
        run: yarn rollup
  ubuntu-cuda:
    name: ubuntu-cuda node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version: ['18.x', '20.x']
    steps:
      - uses: Jimver/cuda-toolkit@v0.2.16
        id: cuda-toolkit
        with:
          cuda: '12.5.0'
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - name: Test rollup
        run: yarn rollup
